title: Kyle'Log
name: "Kaihua(Kyle) Tang's Tech Blog"
author: Kaihua Tang
baseurl: "/kyle-blog"
description: Document my learning notes.
profile_url: "https://kaihuatang.github.io/"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3