title: Kyle's Blog
name: "Kaihua(Kyle) Tang's Blog"
author: Kaihua Tang
twitter_username: northShepherd_
baseurl: "/kyle-blog"
description: Document my learning notes.
profile_url: "https://kaihuatang.github.io/"

# Build settings
markdown: kramdown
highlighter: rouge
future: true
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3
